BINARY := {{.Name.Kebab}}
CMD    := ./cmd/{{.Name.Snake}}

.PHONY: build run test vet fmt tidy clean

build:
	go build -o bin/$(BINARY) $(CMD)

run:
	go run $(CMD)

test:
	go test ./...

vet:
	go vet ./...

fmt:
	gofmt -w .

tidy:
	go mod tidy

clean:
	rm -rf bin
